plugins:
  - prettier
env:
  node: true
  es6: true
extends:
  - "eslint:recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: {
  "prettier/prettier": "error"
}
